import type { Tool } from "./search";

/**
 * Tools shown as cards in the homepage and category page grids.
 * One card per tool TYPE — not per format or format pair.
 */
export const gridTools: Tool[] = [
	{
		title: "Image Convert",
		description: "Convert between HEIC, PNG, JPG, WebP, AVIF, and more",
		href: "/image/convert",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "Image Compress",
		description: "Reduce image file size with adjustable quality",
		href: "/image/compress",
		icon: "FileArchive",
		iconColor: "text-blue-500",
		iconBg: "bg-blue-50 dark:bg-blue-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "Image Resize",
		description: "Resize images by pixels, percentage, or presets",
		href: "/image/resize",
		icon: "Scaling",
		iconColor: "text-orange-500",
		iconBg: "bg-orange-50 dark:bg-orange-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "Image Crop",
		description: "Crop images with custom or preset aspect ratios",
		href: "/image/crop",
		icon: "Crop",
		iconColor: "text-lime-500",
		iconBg: "bg-lime-50 dark:bg-lime-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "Image Rotate & Flip",
		description:
			"Rotate images 90/180/270 degrees or flip horizontally and vertically",
		href: "/image/rotate",
		icon: "RotateCw",
		iconColor: "text-cyan-500",
		iconBg: "bg-cyan-50 dark:bg-cyan-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "EXIF Viewer",
		description: "View and strip photo metadata",
		href: "/image/exif",
		icon: "ScanSearch",
		iconColor: "text-teal-500",
		iconBg: "bg-teal-50 dark:bg-teal-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "Images to PDF",
		description: "Combine multiple images into a single PDF",
		href: "/image/to-pdf",
		icon: "FileImage",
		iconColor: "text-rose-500",
		iconBg: "bg-rose-50 dark:bg-rose-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "Remove Background",
		description: "Remove image backgrounds using AI, locally in your browser",
		href: "/image/remove-background",
		icon: "Eraser",
		iconColor: "text-purple-500",
		iconBg: "bg-purple-50 dark:bg-purple-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "Image Watermark",
		description: "Add text watermarks to images with adjustable placement",
		href: "/image/watermark",
		icon: "Stamp",
		iconColor: "text-pink-500",
		iconBg: "bg-pink-50 dark:bg-pink-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "Favicon Generator",
		description: "Generate multi-size .ico favicons from any image",
		href: "/image/favicon-generator",
		icon: "Image",
		iconColor: "text-yellow-500",
		iconBg: "bg-yellow-50 dark:bg-yellow-950/40",
		category: "Image Tools",
		categoryHref: "/image",
	},
	{
		title: "PDF to Image",
		description: "Convert PDF pages to JPG or PNG images",
		href: "/pdf/pdf-to-jpg",
		icon: "FileOutput",
		iconColor: "text-indigo-500",
		iconBg: "bg-indigo-50 dark:bg-indigo-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
	},
	{
		title: "Merge PDFs",
		description: "Combine multiple PDF files into one document",
		href: "/pdf/merge",
		icon: "Merge",
		iconColor: "text-sky-500",
		iconBg: "bg-sky-50 dark:bg-sky-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
	},
	{
		title: "Compress PDF",
		description: "Reduce PDF file size by re-rendering at lower quality",
		href: "/pdf/compress",
		icon: "FileArchive",
		iconColor: "text-emerald-500",
		iconBg: "bg-emerald-50 dark:bg-emerald-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
	},
	{
		title: "Split PDF",
		description: "Split a PDF into individual pages or custom ranges",
		href: "/pdf/split",
		icon: "Scissors",
		iconColor: "text-rose-500",
		iconBg: "bg-rose-50 dark:bg-rose-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
	},
	{
		title: "Rotate PDF",
		description: "Rotate PDF pages by 90, 180, or 270 degrees",
		href: "/pdf/rotate",
		icon: "RotateCw",
		iconColor: "text-amber-500",
		iconBg: "bg-amber-50 dark:bg-amber-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
	},
	{
		title: "PDF to Text",
		description: "Extract all text content from PDF documents",
		href: "/pdf/pdf-to-text",
		icon: "FileText",
		iconColor: "text-cyan-500",
		iconBg: "bg-cyan-50 dark:bg-cyan-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
	},
	{
		title: "Watermark PDF",
		description: "Add a text watermark to every page of a PDF",
		href: "/pdf/watermark",
		icon: "Stamp",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
	},
	{
		title: "Color Picker",
		description: "Pick colors and convert between HEX, RGB, HSL, OKLCH",
		href: "/developer/color-picker",
		icon: "Palette",
		iconColor: "text-fuchsia-500",
		iconBg: "bg-fuchsia-50 dark:bg-fuchsia-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
	},
	{
		title: "Base64 Image",
		description: "Encode images to base64 or decode base64 to images",
		href: "/developer/base64-image",
		icon: "Code",
		iconColor: "text-green-500",
		iconBg: "bg-green-50 dark:bg-green-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
	},
	{
		title: "QR Code Generator",
		description: "Generate QR codes from text or URLs with custom styling",
		href: "/developer/qr-code",
		icon: "QrCode",
		iconColor: "text-gray-500",
		iconBg: "bg-gray-50 dark:bg-gray-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
	},
	{
		title: "JSON Formatter",
		description: "Validate, format, and minify JSON data",
		href: "/developer/json-formatter",
		icon: "Braces",
		iconColor: "text-yellow-500",
		iconBg: "bg-yellow-50 dark:bg-yellow-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
	},
	{
		title: "Hash Generator",
		description: "Generate MD5, SHA-1, SHA-256, SHA-384, SHA-512 hashes",
		href: "/developer/hash-generator",
		icon: "Hash",
		iconColor: "text-cyan-500",
		iconBg: "bg-cyan-50 dark:bg-cyan-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
	},
	{
		title: "JWT Decoder",
		description: "Decode and inspect JWT tokens with expiration status",
		href: "/developer/jwt-decoder",
		icon: "KeyRound",
		iconColor: "text-orange-500",
		iconBg: "bg-orange-50 dark:bg-orange-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
	},
	{
		title: "SVG Optimizer",
		description: "Minify and optimize SVG files with svgo",
		href: "/vector/svg-optimizer",
		icon: "Minimize2",
		iconColor: "text-amber-500",
		iconBg: "bg-amber-50 dark:bg-amber-950/40",
		category: "Vector Tools",
		categoryHref: "/vector",
	},
];

/**
 * All tools including format-specific landing pages.
 * Used by the command palette and search so users can find any page.
 */
export const allTools: Tool[] = [
	...gridTools,
	// Format-specific conversion landing pages
	{
		title: "HEIC to JPG",
		description: "Convert iPhone HEIC photos to JPG format",
		href: "/image/heic-to-jpg",
		icon: "Camera",
		iconColor: "text-pink-500",
		iconBg: "bg-pink-50 dark:bg-pink-950/40",
	},
	{
		title: "JPG to PNG",
		description: "Convert JPG images to lossless PNG format",
		href: "/image/jpg-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "PNG to JPG",
		description: "Convert PNG images to compact JPG format",
		href: "/image/png-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "WebP to JPG",
		description: "Convert WebP images to universally compatible JPG",
		href: "/image/webp-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "WebP to PNG",
		description: "Convert WebP images to lossless PNG with transparency",
		href: "/image/webp-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "JPG to WebP",
		description: "Convert JPG images to modern WebP format",
		href: "/image/jpg-to-webp",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "PNG to WebP",
		description: "Convert PNG images to efficient WebP format",
		href: "/image/png-to-webp",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "SVG to PNG",
		description: "Rasterize SVG vector graphics to PNG images",
		href: "/image/svg-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "AVIF to JPG",
		description: "Convert AVIF images to widely compatible JPG",
		href: "/image/avif-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "AVIF to PNG",
		description: "Convert AVIF images to lossless PNG format",
		href: "/image/avif-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "GIF to JPG",
		description: "Convert GIF images to compact JPG format",
		href: "/image/gif-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "SVG to JPG",
		description: "Convert SVG vector graphics to JPG images",
		href: "/image/svg-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "SVG to WebP",
		description: "Convert SVG vector graphics to WebP images",
		href: "/image/svg-to-webp",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "TIFF to JPG",
		description: "Convert TIFF images to compact JPG format",
		href: "/image/tiff-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "TIFF to PNG",
		description: "Convert TIFF images to lossless PNG format",
		href: "/image/tiff-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "ICO to PNG",
		description: "Extract favicon ICO images as PNG",
		href: "/image/ico-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "ICO to JPG",
		description: "Convert ICO favicon files to JPG images",
		href: "/image/ico-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "JXL to JPG",
		description: "Convert JPEG XL images to universally compatible JPG",
		href: "/image/jxl-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "JXL to PNG",
		description: "Convert JPEG XL images to lossless PNG format",
		href: "/image/jxl-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	// Niche format catch-all converter pages
	{
		title: "PSD Converter",
		description: "Convert Photoshop PSD files to JPG, PNG, WebP, or AVIF",
		href: "/image/psd-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "PSB Converter",
		description:
			"Convert Photoshop Large Document PSB files to JPG, PNG, WebP, or AVIF",
		href: "/image/psb-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "TGA Converter",
		description: "Convert Targa TGA textures to standard image formats",
		href: "/image/tga-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "HDR Converter",
		description: "Convert Radiance HDR images to JPG, PNG, or WebP",
		href: "/image/hdr-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "EXR Converter",
		description: "Convert OpenEXR images to JPG, PNG, WebP, or AVIF",
		href: "/image/exr-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "DDS Converter",
		description: "Convert DDS game textures to standard image formats",
		href: "/image/dds-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "PCX Converter",
		description: "Convert legacy PCX images to modern formats",
		href: "/image/pcx-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "Netpbm Converter",
		description: "Convert PBM, PGM, PPM, PNM, PAM, PFM to standard formats",
		href: "/image/netpbm-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "FITS Converter",
		description: "Convert FITS astronomy images to JPG, PNG, or WebP",
		href: "/image/fits-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "DICOM Converter",
		description: "Convert DICOM medical images to JPG or PNG",
		href: "/image/dcm-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "Camera RAW Converter",
		description: "Convert CR2, NEF, ARW, DNG and 20+ RAW formats",
		href: "/image/raw-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "JP2 Converter",
		description: "Convert JPEG 2000 (JP2, J2K) to JPG, PNG, or WebP",
		href: "/image/jp2-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "ICNS Converter",
		description: "Convert macOS ICNS app icons to PNG or JPG",
		href: "/image/icns-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "EPS Converter",
		description: "Extract preview images from EPS files",
		href: "/image/eps-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "AI Converter",
		description: "Convert Adobe Illustrator AI files to JPG, PNG, or WebP",
		href: "/image/ai-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "Legacy Image Converter",
		description: "Convert SGI, Sun Raster, WBMP, PCD, PICT, SFW formats",
		href: "/image/legacy-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "XCF Converter",
		description: "Convert GIMP XCF files to JPG, PNG, WebP, or AVIF",
		href: "/image/xcf-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "X Window Converter",
		description: "Convert XBM, XPM, and XWD files to standard formats",
		href: "/image/xwindow-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "XPS Converter",
		description: "Extract images from XPS/OXPS documents",
		href: "/image/xps-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "ODG Converter",
		description: "Convert OpenDocument Graphics to standard formats",
		href: "/image/odg-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "SVGZ Converter",
		description: "Decompress SVGZ files and convert to JPG, PNG, or WebP",
		href: "/image/svgz-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "CDR Converter",
		description: "Convert CorelDRAW CDR files to JPG, PNG, or WebP",
		href: "/image/cdr-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "Visio Converter",
		description: "Convert Visio VSD/VSDX diagrams to JPG, PNG, or WebP",
		href: "/image/vsd-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "PUB Converter",
		description: "Extract images from Microsoft Publisher PUB files",
		href: "/image/pub-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	{
		title: "EMF Converter",
		description: "Convert Windows EMF metafiles to JPG, PNG, or WebP",
		href: "/image/emf-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
	},
	// Format-specific PDF conversion landing pages
	{
		title: "PDF to PNG",
		description: "Convert PDF pages to lossless PNG images",
		href: "/pdf/pdf-to-png",
		icon: "FileOutput",
		iconColor: "text-indigo-500",
		iconBg: "bg-indigo-50 dark:bg-indigo-950/40",
	},
	// Format-specific compression landing pages
	{
		title: "Compress JPG",
		description: "Reduce JPG file size with adjustable quality",
		href: "/image/compress-jpg",
		icon: "FileArchive",
		iconColor: "text-blue-500",
		iconBg: "bg-blue-50 dark:bg-blue-950/40",
	},
	{
		title: "Compress PNG",
		description: "Reduce PNG file size with color quantization",
		href: "/image/compress-png",
		icon: "FileArchive",
		iconColor: "text-emerald-500",
		iconBg: "bg-emerald-50 dark:bg-emerald-950/40",
	},
	{
		title: "Compress WebP",
		description: "Reduce WebP file size with adjustable quality",
		href: "/image/compress-webp",
		icon: "FileArchive",
		iconColor: "text-cyan-500",
		iconBg: "bg-cyan-50 dark:bg-cyan-950/40",
	},
	{
		title: "Compress GIF",
		description: "Reduce animated GIF file size with lossy compression",
		href: "/image/compress-gif",
		icon: "FileArchive",
		iconColor: "text-amber-500",
		iconBg: "bg-amber-50 dark:bg-amber-950/40",
	},
];
