import type { Tool } from "./search";

/**
 * Tools shown as cards in the homepage and category page grids.
 * One card per tool TYPE — not per format or format pair.
 */
export const gridTools: Tool[] = [
	{
		title: "Image Convert",
		description: "Convert between HEIC, PNG, JPG, WebP, AVIF, and more",
		href: "/image/convert",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"photo",
			"picture",
			"format",
			"transform",
			"batch",
			"JPEG",
			"TIFF",
			"GIF",
			"BMP",
			"ICO",
			"HEIF",
			"change format",
			"file type",
		],
	},
	{
		title: "Image Compress",
		description: "Reduce image file size with adjustable quality",
		href: "/image/compress",
		icon: "FileArchive",
		iconColor: "text-blue-500",
		iconBg: "bg-blue-50 dark:bg-blue-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"optimize",
			"shrink",
			"smaller",
			"minify",
			"squeeze",
			"photo",
			"picture",
			"lossy",
			"lossless",
			"file size",
			"reduce size",
			"kb",
			"web optimization",
		],
	},
	{
		title: "Image Resize",
		description: "Resize images by pixels, percentage, or presets",
		href: "/image/resize",
		icon: "Scaling",
		iconColor: "text-orange-500",
		iconBg: "bg-orange-50 dark:bg-orange-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"scale",
			"dimensions",
			"width",
			"height",
			"enlarge",
			"shrink",
			"thumbnail",
			"downsample",
			"upscale",
			"resolution",
			"aspect ratio",
			"px",
			"social media",
		],
	},
	{
		title: "Image Crop",
		description: "Crop images with custom or preset aspect ratios",
		href: "/image/crop",
		icon: "Crop",
		iconColor: "text-lime-500",
		iconBg: "bg-lime-50 dark:bg-lime-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"trim",
			"cut",
			"clip",
			"selection",
			"square",
			"16:9",
			"4:3",
			"portrait",
			"landscape",
		],
	},
	{
		title: "Image Rotate & Flip",
		description:
			"Rotate images 90/180/270 degrees or flip horizontally and vertically",
		href: "/image/rotate",
		icon: "RotateCw",
		iconColor: "text-cyan-500",
		iconBg: "bg-cyan-50 dark:bg-cyan-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"mirror",
			"orientation",
			"turn",
			"spin",
			"upside down",
			"landscape",
			"portrait",
		],
	},
	{
		title: "EXIF Viewer",
		description: "View and strip photo metadata",
		href: "/image/exif",
		icon: "ScanSearch",
		iconColor: "text-teal-500",
		iconBg: "bg-teal-50 dark:bg-teal-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"GPS",
			"location",
			"camera",
			"IPTC",
			"XMP",
			"geotag",
			"geolocation",
			"date taken",
			"exposure",
			"aperture",
			"lens",
			"remove metadata",
			"privacy",
		],
	},
	{
		title: "EXIF Metadata Remover",
		description: "Strip GPS, camera info, and all metadata from photos",
		href: "/image/strip-metadata",
		icon: "ShieldX",
		iconColor: "text-red-500",
		iconBg: "bg-red-50 dark:bg-red-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"EXIF",
			"GPS",
			"geotag",
			"privacy",
			"camera info",
			"photo metadata",
			"IPTC",
			"XMP",
			"strip GPS",
			"journalist",
			"activist",
			"social media",
			"batch strip",
		],
	},
	{
		title: "Images to PDF",
		description: "Combine multiple images into a single PDF",
		href: "/image/to-pdf",
		icon: "FileImage",
		iconColor: "text-rose-500",
		iconBg: "bg-rose-50 dark:bg-rose-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"merge images",
			"photo book",
			"JPG to PDF",
			"PNG to PDF",
			"picture to PDF",
			"scan",
			"collage",
			"document",
			"portfolio",
		],
	},
	{
		title: "Remove Background",
		description: "Remove image backgrounds using AI, locally in your browser",
		href: "/image/remove-background",
		icon: "Eraser",
		iconColor: "text-purple-500",
		iconBg: "bg-purple-50 dark:bg-purple-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"cutout",
			"transparent",
			"alpha",
			"mask",
			"portrait",
			"bg remove",
			"foreground",
			"matting",
			"silhouette",
			"subject",
		],
	},
	{
		title: "Image Watermark",
		description: "Add text watermarks to images with adjustable placement",
		href: "/image/watermark",
		icon: "Stamp",
		iconColor: "text-pink-500",
		iconBg: "bg-pink-50 dark:bg-pink-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: ["copyright", "overlay", "branding", "protect", "stamp", "logo"],
	},
	{
		title: "Favicon Generator",
		description: "Generate multi-size .ico favicons from any image",
		href: "/image/favicon-generator",
		icon: "Image",
		iconColor: "text-yellow-500",
		iconBg: "bg-yellow-50 dark:bg-yellow-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"ico",
			"website icon",
			"browser icon",
			"tab icon",
			"app icon",
			"favicon.ico",
			"shortcut icon",
			"apple-touch-icon",
			"PWA icon",
			"16x16",
			"32x32",
		],
	},
	{
		title: "PDF to Image",
		description: "Convert PDF pages to JPG or PNG images",
		href: "/pdf/pdf-to-jpg",
		icon: "FileOutput",
		iconColor: "text-indigo-500",
		iconBg: "bg-indigo-50 dark:bg-indigo-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: [
			"render",
			"extract",
			"screenshot",
			"rasterize",
			"preview",
			"thumbnail",
			"export",
		],
	},
	{
		title: "Merge PDFs",
		description: "Combine multiple PDF files into one document",
		href: "/pdf/merge",
		icon: "Merge",
		iconColor: "text-sky-500",
		iconBg: "bg-sky-50 dark:bg-sky-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: ["combine", "join", "append", "concatenate", "unite"],
	},
	{
		title: "Compress PDF",
		description: "Reduce PDF file size by re-rendering at lower quality",
		href: "/pdf/compress",
		icon: "FileArchive",
		iconColor: "text-emerald-500",
		iconBg: "bg-emerald-50 dark:bg-emerald-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: [
			"optimize",
			"shrink",
			"smaller",
			"squeeze",
			"reduce PDF",
			"email attachment",
		],
	},
	{
		title: "Split PDF",
		description: "Split a PDF into individual pages or custom ranges",
		href: "/pdf/split",
		icon: "Scissors",
		iconColor: "text-rose-500",
		iconBg: "bg-rose-50 dark:bg-rose-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: ["extract pages", "separate", "divide", "page range"],
	},
	{
		title: "Rotate PDF",
		description: "Rotate PDF pages by 90, 180, or 270 degrees",
		href: "/pdf/rotate",
		icon: "RotateCw",
		iconColor: "text-amber-500",
		iconBg: "bg-amber-50 dark:bg-amber-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: ["turn", "orientation", "landscape", "portrait", "upside down"],
	},
	{
		title: "PDF to Text",
		description: "Extract all text content from PDF documents",
		href: "/pdf/pdf-to-text",
		icon: "FileText",
		iconColor: "text-cyan-500",
		iconBg: "bg-cyan-50 dark:bg-cyan-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: ["OCR", "copy text", "read PDF", "plain text", "text extraction"],
	},
	{
		title: "Watermark PDF",
		description: "Add a text watermark to every page of a PDF",
		href: "/pdf/watermark",
		icon: "Stamp",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: [
			"copyright",
			"overlay",
			"branding",
			"stamp",
			"confidential",
			"draft",
		],
	},
	{
		title: "Reorder PDF Pages",
		description: "Drag and drop to rearrange or remove PDF pages",
		href: "/pdf/reorder",
		icon: "ArrowUpDown",
		iconColor: "text-teal-500",
		iconBg: "bg-teal-50 dark:bg-teal-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: [
			"rearrange",
			"drag and drop",
			"sort pages",
			"remove page",
			"delete page",
			"organize PDF",
			"page order",
		],
	},
	{
		title: "Color Picker",
		description: "Pick colors and convert between HEX, RGB, HSL, OKLCH",
		href: "/developer/color-picker",
		icon: "Palette",
		iconColor: "text-fuchsia-500",
		iconBg: "bg-fuchsia-50 dark:bg-fuchsia-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"eyedropper",
			"colour",
			"hex code",
			"css color",
			"palette",
			"swatch",
			"color converter",
			"HTML color",
			"color code",
		],
	},
	{
		title: "Base64 Image",
		description: "Encode images to base64 or decode base64 to images",
		href: "/developer/base64-image",
		icon: "Code",
		iconColor: "text-green-500",
		iconBg: "bg-green-50 dark:bg-green-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"data URI",
			"data URL",
			"inline image",
			"embed",
			"encoding",
			"base 64",
			"base64 encode",
			"base64 decode",
			"CSS background",
		],
	},
	{
		title: "QR Code Generator",
		description: "Generate QR codes from text or URLs with custom styling",
		href: "/developer/qr-code",
		icon: "QrCode",
		iconColor: "text-gray-500",
		iconBg: "bg-gray-50 dark:bg-gray-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"barcode",
			"scan",
			"matrix code",
			"2D code",
			"link",
			"share",
			"wifi",
			"vcard",
		],
	},
	{
		title: "JSON Formatter",
		description: "Validate, format, and minify JSON data",
		href: "/developer/json-formatter",
		icon: "Braces",
		iconColor: "text-yellow-500",
		iconBg: "bg-yellow-50 dark:bg-yellow-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"beautify",
			"prettify",
			"lint",
			"viewer",
			"parse",
			"indent",
			"tree view",
			"JSON validator",
			"pretty print",
			"compact",
			"minifier",
		],
	},
	{
		title: "Hash Generator",
		description: "Generate MD5, SHA-1, SHA-256, SHA-384, SHA-512 hashes",
		href: "/developer/hash-generator",
		icon: "Hash",
		iconColor: "text-cyan-500",
		iconBg: "bg-cyan-50 dark:bg-cyan-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"checksum",
			"digest",
			"fingerprint",
			"integrity",
			"verify",
			"crypto",
			"file hash",
			"calculator",
		],
	},
	{
		title: "JWT Decoder",
		description: "Decode and inspect JWT tokens with expiration status",
		href: "/developer/jwt-decoder",
		icon: "KeyRound",
		iconColor: "text-orange-500",
		iconBg: "bg-orange-50 dark:bg-orange-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"JSON Web Token",
			"bearer token",
			"auth token",
			"claims",
			"payload",
			"header",
			"signature",
			"OAuth",
		],
	},
	{
		title: "SVG Optimizer",
		description: "Minify and optimize SVG files with svgo",
		href: "/vector/svg-optimizer",
		icon: "Minimize2",
		iconColor: "text-amber-500",
		iconBg: "bg-amber-50 dark:bg-amber-950/40",
		category: "Vector Tools",
		categoryHref: "/vector",
		keywords: [
			"clean SVG",
			"compress SVG",
			"vector",
			"minify SVG",
			"SVG cleaner",
			"reduce SVG",
			"SVGO",
			"inline SVG",
		],
	},
	{
		title: "PDF Page Numbers",
		description: "Add page numbers to every page of a PDF",
		href: "/pdf/page-numbers",
		icon: "ListOrdered",
		iconColor: "text-blue-500",
		iconBg: "bg-blue-50 dark:bg-blue-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: ["pagination", "footer", "header", "numbering", "Bates stamp"],
	},
	{
		title: "Protect PDF",
		description: "Add password protection and restrict permissions",
		href: "/pdf/protect",
		icon: "Lock",
		iconColor: "text-red-500",
		iconBg: "bg-red-50 dark:bg-red-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: [
			"encrypt",
			"lock",
			"secure",
			"password",
			"restrict",
			"read only",
		],
	},
	{
		title: "Unlock PDF",
		description: "Remove password protection from PDF documents",
		href: "/pdf/unlock",
		icon: "LockOpen",
		iconColor: "text-green-500",
		iconBg: "bg-green-50 dark:bg-green-950/40",
		category: "PDF Tools",
		categoryHref: "/pdf",
		keywords: ["decrypt", "unprotect", "remove password", "open locked"],
	},
	{
		title: "Image Filters",
		description: "Apply grayscale, sepia, blur, brightness, and more effects",
		href: "/image/filters",
		icon: "SlidersHorizontal",
		iconColor: "text-fuchsia-500",
		iconBg: "bg-fuchsia-50 dark:bg-fuchsia-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"effects",
			"contrast",
			"saturation",
			"invert",
			"hue",
			"sharpen",
			"vignette",
			"photo edit",
			"adjust",
		],
	},
	{
		title: "Color Palette Extractor",
		description: "Extract dominant colors from any image as hex, RGB, and HSL",
		href: "/image/color-palette",
		icon: "Palette",
		iconColor: "text-purple-500",
		iconBg: "bg-purple-50 dark:bg-purple-950/40",
		category: "Image Tools",
		categoryHref: "/image",
		keywords: [
			"extract colors",
			"dominant colors",
			"hex",
			"RGB",
			"HSL",
			"swatch",
			"brand colors",
			"color scheme",
			"design",
			"median cut",
		],
	},
	{
		title: "Regex Tester",
		description: "Test regular expressions with match highlighting",
		href: "/developer/regex-tester",
		icon: "Regex",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"regexp",
			"pattern",
			"regex101",
			"PCRE",
			"capture group",
			"replace",
		],
	},
	{
		title: "Timestamp Converter",
		description: "Convert between Unix timestamps and human-readable dates",
		href: "/developer/timestamp-converter",
		icon: "Clock",
		iconColor: "text-blue-500",
		iconBg: "bg-blue-50 dark:bg-blue-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"epoch",
			"datetime",
			"milliseconds",
			"ISO 8601",
			"date format",
			"UTC",
			"time zone",
		],
	},
	{
		title: "UUID Generator",
		description: "Generate and validate UUID v4 and v7 identifiers",
		href: "/developer/uuid-generator",
		icon: "Fingerprint",
		iconColor: "text-emerald-500",
		iconBg: "bg-emerald-50 dark:bg-emerald-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: ["GUID", "unique ID", "random ID", "identifier", "v4", "v7"],
	},
	{
		title: "URL Encoder / Decoder",
		description: "Encode, decode, and parse URL components",
		href: "/developer/url-encoder",
		icon: "Link",
		iconColor: "text-sky-500",
		iconBg: "bg-sky-50 dark:bg-sky-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"percent encoding",
			"URI",
			"encodeURI",
			"query string",
			"URL parse",
			"encodeURIComponent",
			"urlencode",
			"urldecode",
			"escape",
		],
	},
	{
		title: "Text Diff",
		description: "Compare two blocks of text with line-level highlighting",
		href: "/developer/text-diff",
		icon: "ArrowLeftRight",
		iconColor: "text-amber-500",
		iconBg: "bg-amber-50 dark:bg-amber-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"compare",
			"difference",
			"merge",
			"patch",
			"changes",
			"side by side",
			"unified diff",
			"diff checker",
			"file compare",
		],
	},
	{
		title: "Markdown Preview",
		description: "Live Markdown editor with GitHub Flavored Markdown support",
		href: "/developer/markdown-preview",
		icon: "FileText",
		iconColor: "text-gray-500",
		iconBg: "bg-gray-50 dark:bg-gray-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"md",
			"GFM",
			"render",
			"editor",
			"markdown to HTML",
			"readme",
			"markdown editor",
			"live preview",
		],
	},
	{
		title: "Word Counter",
		description:
			"Count characters, words, sentences, and paragraphs with reading time",
		href: "/developer/word-counter",
		icon: "LetterText",
		iconColor: "text-teal-500",
		iconBg: "bg-teal-50 dark:bg-teal-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"character count",
			"text analysis",
			"reading time",
			"letter count",
			"text length",
			"wpm",
			"essay",
			"blog post",
		],
	},
	{
		title: "CSS Formatter",
		description: "Minify or beautify CSS with size comparison",
		href: "/developer/css-formatter",
		icon: "Paintbrush",
		iconColor: "text-blue-500",
		iconBg: "bg-blue-50 dark:bg-blue-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"minify CSS",
			"beautify CSS",
			"prettify",
			"compress CSS",
			"format CSS",
			"stylesheet",
			"CSS optimizer",
			"whitespace",
		],
	},
	{
		title: "Case Converter",
		description:
			"Convert text between camelCase, snake_case, kebab-case, and more",
		href: "/developer/case-converter",
		icon: "ALargeSmall",
		iconColor: "text-indigo-500",
		iconBg: "bg-indigo-50 dark:bg-indigo-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"naming convention",
			"snake_case",
			"kebab-case",
			"PascalCase",
			"CONSTANT_CASE",
			"variable name",
			"identifier",
			"programming style",
			"dot.case",
			"Title Case",
		],
	},
	{
		title: "JSON ↔ CSV Converter",
		description: "Convert between JSON arrays and CSV with nested flattening",
		href: "/developer/json-csv",
		icon: "ArrowLeftRight",
		iconColor: "text-green-500",
		iconBg: "bg-green-50 dark:bg-green-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"spreadsheet",
			"Excel",
			"table",
			"data export",
			"data import",
			"tabular",
			"RFC 4180",
			"TSV",
			"flatten",
			"nested JSON",
		],
	},
	{
		title: "CRON Expression Parser",
		description: "Parse cron expressions into human-readable schedules",
		href: "/developer/cron-parser",
		icon: "Clock",
		iconColor: "text-orange-500",
		iconBg: "bg-orange-50 dark:bg-orange-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"crontab",
			"schedule",
			"recurring",
			"task scheduler",
			"Unix",
			"Linux",
			"job scheduler",
			"interval",
			"automation",
		],
	},
	{
		title: "Lorem Ipsum Generator",
		description: "Generate placeholder text with configurable length",
		href: "/developer/lorem-ipsum",
		icon: "AlignLeft",
		iconColor: "text-stone-500",
		iconBg: "bg-stone-50 dark:bg-stone-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"placeholder",
			"dummy text",
			"filler",
			"lipsum",
			"sample text",
			"Cicero",
			"typesetting",
			"mock content",
		],
	},
	{
		title: "SQL Formatter",
		description: "Beautify and minify SQL queries across 10 dialects",
		href: "/developer/sql-formatter",
		icon: "Database",
		iconColor: "text-rose-500",
		iconBg: "bg-rose-50 dark:bg-rose-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"sql beautifier",
			"pretty print sql",
			"mysql",
			"postgresql",
			"sqlite",
			"mariadb",
			"bigquery",
			"snowflake",
			"redshift",
			"t-sql",
			"plsql",
			"query",
			"database",
			"prettify",
			"minify",
		],
	},
	{
		title: "HTML Formatter",
		description: "Beautify messy HTML markup with configurable indent",
		href: "/developer/html-formatter",
		icon: "FileCode",
		iconColor: "text-orange-500",
		iconBg: "bg-orange-50 dark:bg-orange-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"html beautifier",
			"pretty print html",
			"indent html",
			"prettify markup",
			"clean html",
			"reformat html",
			"web page",
			"dom",
			"template",
			"beautify",
		],
	},
	{
		title: "YAML \u2194 JSON",
		description: "Convert between YAML and JSON with validation",
		href: "/developer/yaml-json",
		icon: "FileCode",
		iconColor: "text-indigo-500",
		iconBg: "bg-indigo-50 dark:bg-indigo-950/40",
		category: "Developer Tools",
		categoryHref: "/developer",
		keywords: [
			"YAML",
			"YML",
			"configuration",
			"Kubernetes",
			"Docker",
			"CI/CD",
			"Ansible",
			"config file",
			"k8s",
			"docker-compose",
			"CloudFormation",
			"Helm",
		],
	},
];

/**
 * All tools including format-specific landing pages.
 * Used by the command palette and search so users can find any page.
 */
export const allTools: Tool[] = [
	...gridTools,
	// Format-specific conversion landing pages
	{
		title: "HEIC to JPG",
		description: "Convert iPhone HEIC photos to JPG format",
		href: "/image/heic-to-jpg",
		icon: "Camera",
		iconColor: "text-pink-500",
		iconBg: "bg-pink-50 dark:bg-pink-950/40",
		keywords: [
			"iOS",
			"Apple",
			"HEIF",
			"Live Photo",
			"JPEG",
			"iPhone photo",
			"iPad",
		],
	},
	{
		title: "HEIC to WebP",
		description: "Convert iPhone HEIC photos to modern WebP format",
		href: "/image/heic-to-webp",
		icon: "Camera",
		iconColor: "text-pink-500",
		iconBg: "bg-pink-50 dark:bg-pink-950/40",
		keywords: ["iOS", "Apple", "HEIF", "iPhone photo", "iPad", "modern format"],
	},
	{
		title: "HEIC to PNG",
		description: "Convert iPhone HEIC photos to lossless PNG format",
		href: "/image/heic-to-png",
		icon: "Camera",
		iconColor: "text-pink-500",
		iconBg: "bg-pink-50 dark:bg-pink-950/40",
		keywords: [
			"iOS",
			"Apple",
			"HEIF",
			"lossless",
			"iPhone photo",
			"iPad",
			"transparency",
		],
	},
	{
		title: "JPG to PNG",
		description: "Convert JPG images to lossless PNG format",
		href: "/image/jpg-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["JPEG", "lossless", "transparency", "alpha channel"],
	},
	{
		title: "PNG to JPG",
		description: "Convert PNG images to compact JPG format",
		href: "/image/png-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["JPEG", "lossy", "smaller", "photo"],
	},
	{
		title: "WebP to JPG",
		description: "Convert WebP images to universally compatible JPG",
		href: "/image/webp-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["Google", "web image", "JPEG", "Chrome"],
	},
	{
		title: "WebP to PNG",
		description: "Convert WebP images to lossless PNG with transparency",
		href: "/image/webp-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["Google", "web image", "lossless", "Chrome"],
	},
	{
		title: "JPG to WebP",
		description: "Convert JPG images to modern WebP format",
		href: "/image/jpg-to-webp",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["JPEG", "next-gen", "web", "smaller"],
	},
	{
		title: "PNG to WebP",
		description: "Convert PNG images to efficient WebP format",
		href: "/image/png-to-webp",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["next-gen", "web", "smaller", "alpha"],
	},
	{
		title: "SVG to PNG",
		description: "Rasterize SVG vector graphics to PNG images",
		href: "/image/svg-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["vector to raster", "scalable vector", "export"],
	},
	{
		title: "AVIF to JPG",
		description: "Convert AVIF images to widely compatible JPG",
		href: "/image/avif-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["AV1", "next-gen", "JPEG", "modern format"],
	},
	{
		title: "AVIF to PNG",
		description: "Convert AVIF images to lossless PNG format",
		href: "/image/avif-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["AV1", "next-gen", "lossless", "modern format"],
	},
	{
		title: "GIF to JPG",
		description: "Convert GIF images to compact JPG format",
		href: "/image/gif-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["animated", "frame", "still", "JPEG"],
	},
	{
		title: "GIF to PNG",
		description: "Convert GIF images to lossless PNG with transparency",
		href: "/image/gif-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["animated", "frame", "transparent", "lossless", "pixel art"],
	},
	{
		title: "BMP to JPG",
		description: "Convert BMP bitmap images to compact JPG format",
		href: "/image/bmp-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["bitmap", "Windows", "Paint", "uncompressed", "scanner", "JPEG"],
	},
	{
		title: "BMP to PNG",
		description: "Convert BMP bitmap images to lossless PNG format",
		href: "/image/bmp-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["bitmap", "Windows", "Paint", "uncompressed", "scanner"],
	},
	{
		title: "BMP to WebP",
		description: "Convert BMP bitmap images to modern WebP format",
		href: "/image/bmp-to-webp",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"bitmap",
			"Windows",
			"Paint",
			"uncompressed",
			"scanner",
			"modern format",
		],
	},
	{
		title: "SVG to JPG",
		description: "Convert SVG vector graphics to JPG images",
		href: "/image/svg-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["vector to raster", "scalable vector", "export", "JPEG"],
	},
	{
		title: "SVG to WebP",
		description: "Convert SVG vector graphics to WebP images",
		href: "/image/svg-to-webp",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["vector to raster", "scalable vector", "export"],
	},
	{
		title: "TIFF to JPG",
		description: "Convert TIFF images to compact JPG format",
		href: "/image/tiff-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["TIF", "print", "publishing", "scan", "document", "JPEG"],
	},
	{
		title: "TIFF to PNG",
		description: "Convert TIFF images to lossless PNG format",
		href: "/image/tiff-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["TIF", "print", "publishing", "scan", "document"],
	},
	{
		title: "ICO to PNG",
		description: "Extract favicon ICO images as PNG",
		href: "/image/ico-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["favicon", "icon", "extract", "Windows icon"],
	},
	{
		title: "ICO to JPG",
		description: "Convert ICO favicon files to JPG images",
		href: "/image/ico-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["favicon", "icon", "Windows icon", "JPEG"],
	},
	{
		title: "ICO to WebP",
		description: "Convert ICO favicon files to WebP images",
		href: "/image/ico-to-webp",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["favicon", "icon", "Windows icon", "modern format"],
	},
	{
		title: "JXL to JPG",
		description: "Convert JPEG XL images to universally compatible JPG",
		href: "/image/jxl-to-jpg",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["JPEG XL", "next-gen", "modern", "JPEG"],
	},
	{
		title: "JXL to PNG",
		description: "Convert JPEG XL images to lossless PNG format",
		href: "/image/jxl-to-png",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["JPEG XL", "next-gen", "modern", "lossless"],
	},
	// Niche format catch-all converter pages
	{
		title: "PSD Converter",
		description: "Convert Photoshop PSD files to JPG, PNG, WebP, or AVIF",
		href: "/image/psd-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["Photoshop", "Adobe", "layers", "design file", ".psd"],
	},
	{
		title: "PSB Converter",
		description:
			"Convert Photoshop Large Document PSB files to JPG, PNG, WebP, or AVIF",
		href: "/image/psb-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["Adobe", "Photoshop", "big PSD", ".psb", "large document"],
	},
	{
		title: "TGA Converter",
		description: "Convert Targa TGA textures to standard image formats",
		href: "/image/tga-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["TARGA", "Truevision", "game texture", "3D", "texture"],
	},
	{
		title: "HDR Converter",
		description: "Convert Radiance HDR images to JPG, PNG, or WebP",
		href: "/image/hdr-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"high dynamic range",
			"tone mapping",
			"HDRI",
			"RGBE",
			"environment map",
			"lighting",
			"panorama",
			"skybox",
			"IBL",
			".hdr",
			"3D",
			"photosphere",
		],
	},
	{
		title: "EXR Converter",
		description: "Convert OpenEXR images to JPG, PNG, WebP, or AVIF",
		href: "/image/exr-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"OpenEXR",
			"ILM",
			"VFX",
			"compositing",
			"film",
			"high dynamic range",
			"rendering",
			"Nuke",
			"Blender",
			"Maya",
			"Houdini",
			"After Effects",
			".exr",
		],
	},
	{
		title: "DDS Converter",
		description: "Convert DDS game textures to standard image formats",
		href: "/image/dds-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"DirectX",
			"DirectDraw Surface",
			"GPU texture",
			"DXT",
			"BC compression",
			"normal map",
			"Unity",
			"Unreal",
			"S3TC",
			"mipmap",
		],
	},
	{
		title: "PCX Converter",
		description: "Convert legacy PCX images to modern formats",
		href: "/image/pcx-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["ZSoft", "PaintBrush", "DOS", "retro", "vintage", "bitmap"],
	},
	{
		title: "Netpbm Converter",
		description: "Convert PBM, PGM, PPM, PNM, PAM, PFM to standard formats",
		href: "/image/netpbm-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"portable bitmap",
			"portable pixmap",
			"portable graymap",
			"Unix",
			"Linux",
		],
	},
	{
		title: "FITS Converter",
		description: "Convert FITS astronomy images to JPG, PNG, or WebP",
		href: "/image/fits-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"telescope",
			"NASA",
			"space",
			"astrophotography",
			"science",
			"star",
			"Hubble",
			"observatory",
			"JWST",
			"FIT",
			".fits",
			"astronomical",
		],
	},
	{
		title: "DICOM Converter",
		description: "Convert DICOM medical images to JPG or PNG",
		href: "/image/dcm-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"DCM",
			"CT scan",
			"CT",
			"MRI",
			"X-ray",
			"xray",
			"radiology",
			"hospital",
			"ultrasound",
			"PACS",
			"medical imaging",
		],
	},
	{
		title: "Camera RAW Converter",
		description: "Convert CR2, NEF, ARW, DNG and 20+ RAW formats",
		href: "/image/raw-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"Canon",
			"Nikon",
			"Sony",
			"Fuji",
			"Fujifilm",
			"ORF",
			"RAF",
			"RW2",
			"CR3",
			"PEF",
			"Panasonic",
			"Olympus",
			"DSLR",
			"mirrorless",
			"digital negative",
			"Pentax",
			"Leica",
			"Hasselblad",
			"raw photo",
			"Lightroom",
		],
	},
	{
		title: "JP2 Converter",
		description: "Convert JPEG 2000 (JP2, J2K) to JPG, PNG, or WebP",
		href: "/image/jp2-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"J2C",
			"JPC",
			"wavelet",
			"JPEG2000",
			".jp2",
			".j2k",
			"JPEG 2000",
		],
	},
	{
		title: "ICNS Converter",
		description: "Convert macOS ICNS app icons to PNG or JPG",
		href: "/image/icns-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["Apple", "Mac icon", "app icon", "macOS app"],
	},
	{
		title: "EPS Converter",
		description: "Extract preview images from EPS files",
		href: "/image/eps-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"Encapsulated PostScript",
			"vector",
			"print",
			"Adobe",
			"Illustrator",
			"clip art",
			"PostScript",
		],
	},
	{
		title: "AI Converter",
		description: "Convert Adobe Illustrator AI files to JPG, PNG, or WebP",
		href: "/image/ai-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"Illustrator",
			"Adobe Illustrator",
			"vector",
			"design",
			"artwork",
			"illustration",
			".ai",
		],
	},
	{
		title: "Legacy Image Converter",
		description: "Convert SGI, Sun Raster, WBMP, PCD, PICT, SFW formats",
		href: "/image/legacy-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"old format",
			"vintage",
			"retro",
			"Silicon Graphics",
			".sgi",
			".ras",
			".wbmp",
			".pcd",
			".pict",
			"Photo CD",
			"Kodak",
		],
	},
	{
		title: "XCF Converter",
		description: "Convert GIMP XCF files to JPG, PNG, WebP, or AVIF",
		href: "/image/xcf-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"GIMP",
			"GNU Image",
			"layers",
			"open source",
			"free editor",
			".xcf",
		],
	},
	{
		title: "X Window Converter",
		description: "Convert XBM, XPM, and XWD files to standard formats",
		href: "/image/xwindow-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"X11",
			"Unix",
			"Linux",
			"X Window System",
			"bitmap",
			"pixmap",
			"window dump",
		],
	},
	{
		title: "XPS Converter",
		description: "Extract images from XPS/OXPS documents",
		href: "/image/xps-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"XML Paper",
			"OXPS",
			"Microsoft",
			"Open XPS",
			"document",
			".xps",
		],
	},
	{
		title: "ODG Converter",
		description: "Convert OpenDocument Graphics to standard formats",
		href: "/image/odg-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["LibreOffice", "Draw", "OpenOffice", "vector", ".odg", "ODF"],
	},
	{
		title: "SVGZ Converter",
		description: "Decompress SVGZ files and convert to JPG, PNG, or WebP",
		href: "/image/svgz-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: ["compressed SVG", "gzipped SVG", "vector", "gzip"],
	},
	{
		title: "CDR Converter",
		description: "Convert CorelDRAW CDR files to JPG, PNG, or WebP",
		href: "/image/cdr-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"CorelDRAW",
			"Corel",
			"Corel Draw",
			"vector",
			"design",
			"illustration",
			".cdr",
		],
	},
	{
		title: "Visio Converter",
		description: "Convert Visio VSD/VSDX diagrams to JPG, PNG, or WebP",
		href: "/image/vsd-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"Microsoft",
			"diagram",
			"flowchart",
			"network diagram",
			"org chart",
			"process flow",
			"UML",
		],
	},
	{
		title: "PUB Converter",
		description: "Extract images from Microsoft Publisher PUB files",
		href: "/image/pub-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"Microsoft",
			"Publisher",
			"publication",
			"flyer",
			"brochure",
			"newsletter",
			"layout",
			".pub",
		],
	},
	{
		title: "EMF Converter",
		description: "Convert Windows EMF metafiles to JPG, PNG, or WebP",
		href: "/image/emf-converter",
		icon: "RefreshCw",
		iconColor: "text-violet-500",
		iconBg: "bg-violet-50 dark:bg-violet-950/40",
		keywords: [
			"Enhanced Metafile",
			"WMF",
			"vector",
			"clipboard",
			"Office",
			"Windows Metafile",
		],
	},
	// Format-specific PDF conversion landing pages
	{
		title: "PDF to PNG",
		description: "Convert PDF pages to lossless PNG images",
		href: "/pdf/pdf-to-png",
		icon: "FileOutput",
		iconColor: "text-indigo-500",
		iconBg: "bg-indigo-50 dark:bg-indigo-950/40",
		keywords: ["render", "rasterize", "high quality", "lossless", "export"],
	},
	// Format-specific compression landing pages
	{
		title: "Compress JPG",
		description: "Reduce JPG file size with adjustable quality",
		href: "/image/compress-jpg",
		icon: "FileArchive",
		iconColor: "text-blue-500",
		iconBg: "bg-blue-50 dark:bg-blue-950/40",
		keywords: ["JPEG", "optimize", "shrink", "reduce", "photo"],
	},
	{
		title: "Compress PNG",
		description: "Reduce PNG file size with color quantization",
		href: "/image/compress-png",
		icon: "FileArchive",
		iconColor: "text-emerald-500",
		iconBg: "bg-emerald-50 dark:bg-emerald-950/40",
		keywords: ["optimize", "quantize", "reduce colors", "pngquant", "palette"],
	},
	{
		title: "Compress WebP",
		description: "Reduce WebP file size with adjustable quality",
		href: "/image/compress-webp",
		icon: "FileArchive",
		iconColor: "text-cyan-500",
		iconBg: "bg-cyan-50 dark:bg-cyan-950/40",
		keywords: ["optimize", "shrink", "reduce", "Google format"],
	},
	{
		title: "Compress GIF",
		description: "Reduce animated GIF file size with lossy compression",
		href: "/image/compress-gif",
		icon: "FileArchive",
		iconColor: "text-amber-500",
		iconBg: "bg-amber-50 dark:bg-amber-950/40",
		keywords: ["optimize", "animated", "animation", "gifsicle"],
	},
];
