import type { Config } from "@react-router/dev/config";

export default {
	ssr: true,
	// All routes are prerendered — no server to handle /__manifest requests.
	// "initial" embeds the full route manifest in the HTML so client-side
	// navigation works on static hosts (S3/CloudFront).
	routeDiscovery: { mode: "initial" },
	prerender: [
		"/",
		"/about",
		"/image",
		"/image/heic-to-jpg",
		"/image/compress",
		"/image/compress-jpg",
		"/image/compress-png",
		"/image/compress-webp",
		"/image/compress-gif",
		"/image/convert",
		"/image/jpg-to-png",
		"/image/png-to-jpg",
		"/image/webp-to-jpg",
		"/image/webp-to-png",
		"/image/jpg-to-webp",
		"/image/png-to-webp",
		"/image/svg-to-png",
		"/image/avif-to-jpg",
		"/image/avif-to-png",
		"/image/gif-to-jpg",
		"/image/resize",
		"/image/crop",
		"/image/rotate",
		"/image/exif",
		"/image/to-pdf",
		"/image/svg-to-jpg",
		"/image/svg-to-webp",
		"/image/remove-background",
		"/image/watermark",
		"/image/tiff-to-jpg",
		"/image/tiff-to-png",
		"/image/ico-to-png",
		"/image/ico-to-jpg",
		"/image/jxl-to-jpg",
		"/image/jxl-to-png",
		"/image/psd-converter",
		"/image/tga-converter",
		"/image/hdr-converter",
		"/image/exr-converter",
		"/image/dds-converter",
		"/image/pcx-converter",
		"/image/netpbm-converter",
		"/image/fits-converter",
		"/image/dcm-converter",
		"/image/raw-converter",
		"/image/jp2-converter",
		"/image/psb-converter",
		"/image/icns-converter",
		"/image/eps-converter",
		"/image/ai-converter",
		"/image/legacy-converter",
		"/image/svgz-converter",
		"/image/xps-converter",
		"/image/odg-converter",
		"/image/xcf-converter",
		"/image/xwindow-converter",
		"/image/cdr-converter",
		"/image/vsd-converter",
		"/image/pub-converter",
		"/image/emf-converter",
		"/image/favicon-generator",
		"/pdf",
		"/pdf/pdf-to-jpg",
		"/pdf/pdf-to-png",
		"/pdf/merge",
		"/pdf/compress",
		"/pdf/split",
		"/pdf/rotate",
		"/pdf/pdf-to-text",
		"/pdf/watermark",
		"/vector",
		"/vector/svg-optimizer",
		"/developer",
		"/developer/color-picker",
		"/developer/base64-image",
		"/developer/qr-code",
		"/developer/json-formatter",
		"/developer/hash-generator",
		"/developer/jwt-decoder",
		"/developer/uuid-generator",
		"/developer/regex-tester",
		"/developer/timestamp-converter",
		"/developer/url-encoder",
		"/developer/text-diff",
		"/developer/markdown-preview",
		"/pdf/page-numbers",
		"/pdf/protect",
		"/pdf/unlock",
		"/image/filters",
	],
} satisfies Config;
