import type { Config } from "@react-router/dev/config";

export default {
	ssr: true,
	prerender: [
		"/",
		"/about",
		"/image",
		"/image/heic-to-jpg",
		"/image/compress",
		"/image/compress-jpg",
		"/image/compress-png",
		"/image/compress-webp",
		"/image/convert",
		"/image/jpg-to-png",
		"/image/png-to-jpg",
		"/image/webp-to-jpg",
		"/image/webp-to-png",
		"/image/jpg-to-webp",
		"/image/png-to-webp",
		"/image/svg-to-png",
		"/image/avif-to-jpg",
		"/image/avif-to-png",
		"/image/gif-to-jpg",
		"/image/resize",
		"/image/exif",
		"/image/to-pdf",
		"/developer",
		"/developer/color-picker",
	],
} satisfies Config;
