import type { Config } from "@react-router/dev/config";

export default {
	ssr: true,
	prerender: [
		"/",
		"/about",
		"/image",
		"/image/heic-to-jpg",
		"/image/compress",
		"/image/compress-jpg",
		"/image/compress-png",
		"/image/compress-webp",
		"/image/compress-gif",
		"/image/convert",
		"/image/jpg-to-png",
		"/image/png-to-jpg",
		"/image/webp-to-jpg",
		"/image/webp-to-png",
		"/image/jpg-to-webp",
		"/image/png-to-webp",
		"/image/svg-to-png",
		"/image/avif-to-jpg",
		"/image/avif-to-png",
		"/image/gif-to-jpg",
		"/image/resize",
		"/image/crop",
		"/image/exif",
		"/image/to-pdf",
		"/image/svg-to-jpg",
		"/image/svg-to-webp",
		"/image/remove-background",
		"/image/tiff-to-jpg",
		"/image/tiff-to-png",
		"/image/ico-to-png",
		"/image/ico-to-jpg",
		"/image/jxl-to-jpg",
		"/image/jxl-to-png",
		"/image/psd-converter",
		"/image/tga-converter",
		"/image/hdr-converter",
		"/image/exr-converter",
		"/image/dds-converter",
		"/image/pcx-converter",
		"/image/netpbm-converter",
		"/image/fits-converter",
		"/image/dcm-converter",
		"/image/raw-converter",
		"/pdf",
		"/pdf/pdf-to-jpg",
		"/pdf/pdf-to-png",
		"/pdf/merge",
		"/pdf/compress",
		"/developer",
		"/developer/color-picker",
		"/developer/base64-image",
		"/developer/qr-code",
	],
} satisfies Config;
