import { index, type RouteConfig, route } from "@react-router/dev/routes";

export default [
	index("routes/home.tsx"),
	route("about", "routes/about.tsx"),
	route("image", "routes/image/index.tsx"),
	route("image/heic-to-jpg", "routes/image/heic-to-jpg.tsx"),
	route("image/compress", "routes/image/compress.tsx"),
	route("image/compress-jpg", "routes/image/compress-jpg.tsx"),
	route("image/compress-png", "routes/image/compress-png.tsx"),
	route("image/compress-webp", "routes/image/compress-webp.tsx"),
	route("image/compress-gif", "routes/image/compress-gif.tsx"),
	route("image/convert", "routes/image/convert.tsx"),
	route("image/jpg-to-png", "routes/image/jpg-to-png.tsx"),
	route("image/png-to-jpg", "routes/image/png-to-jpg.tsx"),
	route("image/webp-to-jpg", "routes/image/webp-to-jpg.tsx"),
	route("image/webp-to-png", "routes/image/webp-to-png.tsx"),
	route("image/jpg-to-webp", "routes/image/jpg-to-webp.tsx"),
	route("image/png-to-webp", "routes/image/png-to-webp.tsx"),
	route("image/svg-to-png", "routes/image/svg-to-png.tsx"),
	route("image/avif-to-jpg", "routes/image/avif-to-jpg.tsx"),
	route("image/avif-to-png", "routes/image/avif-to-png.tsx"),
	route("image/gif-to-jpg", "routes/image/gif-to-jpg.tsx"),
	route("image/resize", "routes/image/resize.tsx"),
	route("image/exif", "routes/image/exif.tsx"),
	route("image/to-pdf", "routes/image/to-pdf.tsx"),
	route("developer", "routes/developer/index.tsx"),
	route("developer/color-picker", "routes/developer/color-picker.tsx"),
] satisfies RouteConfig;
