import { index, type RouteConfig, route } from "@react-router/dev/routes";

export default [
	index("routes/home.tsx"),
	route("about", "routes/about.tsx"),
	route("image", "routes/image/index.tsx"),
	route("image/heic-to-jpg", "routes/image/heic-to-jpg.tsx"),
	route("image/compress", "routes/image/compress.tsx"),
	route("image/compress-jpg", "routes/image/compress-jpg.tsx"),
	route("image/compress-png", "routes/image/compress-png.tsx"),
	route("image/compress-webp", "routes/image/compress-webp.tsx"),
	route("image/compress-gif", "routes/image/compress-gif.tsx"),
	route("image/convert", "routes/image/convert.tsx"),
	route("image/jpg-to-png", "routes/image/jpg-to-png.tsx"),
	route("image/png-to-jpg", "routes/image/png-to-jpg.tsx"),
	route("image/webp-to-jpg", "routes/image/webp-to-jpg.tsx"),
	route("image/webp-to-png", "routes/image/webp-to-png.tsx"),
	route("image/jpg-to-webp", "routes/image/jpg-to-webp.tsx"),
	route("image/png-to-webp", "routes/image/png-to-webp.tsx"),
	route("image/svg-to-png", "routes/image/svg-to-png.tsx"),
	route("image/avif-to-jpg", "routes/image/avif-to-jpg.tsx"),
	route("image/avif-to-png", "routes/image/avif-to-png.tsx"),
	route("image/gif-to-jpg", "routes/image/gif-to-jpg.tsx"),
	route("image/resize", "routes/image/resize.tsx"),
	route("image/crop", "routes/image/crop.tsx"),
	route("image/exif", "routes/image/exif.tsx"),
	route("image/to-pdf", "routes/image/to-pdf.tsx"),
	route("image/svg-to-jpg", "routes/image/svg-to-jpg.tsx"),
	route("image/svg-to-webp", "routes/image/svg-to-webp.tsx"),
	route("image/remove-background", "routes/image/remove-background.tsx"),
	route("image/tiff-to-jpg", "routes/image/tiff-to-jpg.tsx"),
	route("image/tiff-to-png", "routes/image/tiff-to-png.tsx"),
	route("image/ico-to-png", "routes/image/ico-to-png.tsx"),
	route("image/ico-to-jpg", "routes/image/ico-to-jpg.tsx"),
	route("image/jxl-to-jpg", "routes/image/jxl-to-jpg.tsx"),
	route("image/jxl-to-png", "routes/image/jxl-to-png.tsx"),
	route("image/psd-converter", "routes/image/psd-converter.tsx"),
	route("image/tga-converter", "routes/image/tga-converter.tsx"),
	route("image/hdr-converter", "routes/image/hdr-converter.tsx"),
	route("image/exr-converter", "routes/image/exr-converter.tsx"),
	route("image/dds-converter", "routes/image/dds-converter.tsx"),
	route("image/pcx-converter", "routes/image/pcx-converter.tsx"),
	route("image/netpbm-converter", "routes/image/netpbm-converter.tsx"),
	route("image/fits-converter", "routes/image/fits-converter.tsx"),
	route("image/dcm-converter", "routes/image/dcm-converter.tsx"),
	route("image/raw-converter", "routes/image/raw-converter.tsx"),
	route("pdf", "routes/pdf/index.tsx"),
	route("pdf/pdf-to-jpg", "routes/pdf/pdf-to-jpg.tsx"),
	route("pdf/pdf-to-png", "routes/pdf/pdf-to-png.tsx"),
	route("pdf/merge", "routes/pdf/merge.tsx"),
	route("pdf/compress", "routes/pdf/compress.tsx"),
	route("developer", "routes/developer/index.tsx"),
	route("developer/color-picker", "routes/developer/color-picker.tsx"),
	route("developer/base64-image", "routes/developer/base64-image.tsx"),
	route("developer/qr-code", "routes/developer/qr-code.tsx"),
] satisfies RouteConfig;
