import { lazy, Suspense } from "react";
import { LibraryAttribution } from "~/components/tool/library-attribution";
import { ToolPageLayout } from "~/components/tool/tool-page-layout";
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from "~/components/ui/accordion";
import { Spinner } from "~/components/ui/spinner";
import { buildMeta } from "~/lib/seo/meta";
import type { Route } from "./+types/odg-converter";

const ImageConverterTool = lazy(
	() => import("~/features/image-tools/components/image-converter-tool"),
);

export function meta(_args: Route.MetaArgs) {
	return buildMeta({
		title: "Convert ODG Online — Free, Private, No Upload | NoUploads",
		description:
			"Extract the thumbnail from ODG (LibreOffice Draw) files and convert to JPG, PNG, or WebP in your browser. No upload needed.",
		path: "/image/odg-converter",
		keywords:
			"odg to jpg, odg to png, odg converter online, open odg file, libreoffice draw converter, opendocument graphics",
		jsonLdName: "ODG Converter",
	});
}

const ACCEPT = {
	"application/vnd.oasis.opendocument.graphics": [".odg"],
};

const faqItems = [
	{
		question: "What's the history behind the OpenDocument format?",
		answer: (
			<>
				ODG is part of the OpenDocument Format (ODF), an open standard for
				office documents developed by the OASIS consortium and standardized as
				ISO/IEC 26300 in 2006. ODF was created to ensure that documents would
				never be locked into a single vendor's proprietary format. It is
				natively supported by LibreOffice, Apache OpenOffice, and several other
				office suites.{" "}
				<a
					href="https://en.wikipedia.org/wiki/OpenDocument"
					target="_blank"
					rel="noopener"
					className="underline hover:text-foreground transition-colors"
				>
					Source: Wikipedia
				</a>
			</>
		),
	},
	{
		question: "How does this tool extract an image from ODG files?",
		answer:
			"Every ODF-compliant file includes a thumbnail preview at a standard location inside the archive (Thumbnails/thumbnail.png). This tool opens the ZIP, extracts that thumbnail, and converts it to your chosen format. If no thumbnail is found, it falls back to looking for embedded raster images in the Pictures directory. The extraction runs entirely in your browser.",
	},
	{
		question: "What are the constraints of ODG conversion?",
		answer:
			"The embedded thumbnail is typically a low-to-medium resolution preview generated by LibreOffice or OpenOffice when the file was last saved. It reflects the overall appearance of the drawing but not at full vector quality. For high-resolution output, open the ODG file in LibreOffice Draw and export directly. ODG files created by applications that skip the thumbnail spec may not have a usable preview.",
	},
];

export default function OdgConverterPage() {
	return (
		<ToolPageLayout
			title="Convert ODG"
			description="Extract the embedded thumbnail from ODG (LibreOffice Draw) files and convert to JPG, PNG, or WebP — free, private, no upload required."
		>
			<Suspense
				fallback={
					<div className="flex items-center justify-center h-[460px]">
						<Spinner className="size-6" />
					</div>
				}
			>
				<ImageConverterTool accept={ACCEPT} />
			</Suspense>

			<section className="mt-12 mb-8">
				<h2 className="text-lg font-semibold mb-2">About this tool</h2>
				<p className="text-muted-foreground">
					Extracts the embedded thumbnail from ODG files created by LibreOffice
					Draw, Apache OpenOffice Draw, or any ODF-compliant application. The
					decoder opens the ZIP archive and reads the standard ODF thumbnail
					preview, then lets you save it as JPG, PNG, WebP, or AVIF. Handy for
					quickly previewing ODG drawings without installing an office suite.
					The output quality matches whatever thumbnail resolution the
					originating application embedded. All processing happens locally in
					your browser using JSZip.
				</p>
			</section>

			<section>
				<h2 className="text-lg font-semibold mb-4">
					Frequently Asked Questions
				</h2>
				<Accordion type="multiple">
					{faqItems.map((item, i) => (
						// biome-ignore lint/suspicious/noArrayIndexKey: static FAQ list never changes
						<AccordionItem key={i} value={`faq-${i}`}>
							<AccordionTrigger>{item.question}</AccordionTrigger>
							<AccordionContent>
								<p className="text-muted-foreground">{item.answer}</p>
							</AccordionContent>
						</AccordionItem>
					))}
				</Accordion>
			</section>

			<LibraryAttribution packages={["jszip"]} />
		</ToolPageLayout>
	);
}
