import { lazy, Suspense } from "react";
import { LibraryAttribution } from "~/components/tool/library-attribution";
import { ToolPageLayout } from "~/components/tool/tool-page-layout";
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from "~/components/ui/accordion";
import { Spinner } from "~/components/ui/spinner";
import { buildMeta } from "~/lib/seo/meta";
import type { Route } from "./+types/raw-converter";

const ImageConverterTool = lazy(
	() => import("~/features/image-tools/components/image-converter-tool"),
);

export function meta(_args: Route.MetaArgs) {
	return buildMeta({
		title: "Convert Camera RAW Online — CR2, NEF, ARW, DNG & More | NoUploads",
		description:
			"Convert camera RAW files (CR2, NEF, ARW, DNG, RAF, ORF) to JPG, PNG, or WebP in your browser. No upload, no signup.",
		path: "/image/raw-converter",
		keywords:
			"raw to jpg, cr2 converter, nef to jpg, arw converter, dng to jpg online, raw converter online",
		jsonLdName: "Camera RAW Converter",
	});
}

const ACCEPT: Record<string, string[]> = {
	"image/x-adobe-dng": [".dng"],
	"": [
		".cr2",
		".cr3",
		".crw",
		".nef",
		".nrw",
		".arw",
		".sr2",
		".srw",
		".raf",
		".orf",
		".pef",
		".erf",
		".rw2",
		".mrw",
		".mef",
		".mos",
		".kdc",
		".dcr",
		".x3f",
		".3fr",
		".raw",
	],
};

const faqItems = [
	{
		question: "Why do photographers shoot in RAW instead of JPEG?",
		answer: (
			<>
				RAW files contain the unprocessed sensor data captured by a digital
				camera — essentially the raw photon counts from each photosite on the
				image sensor. Unlike JPEG, which bakes in white balance, sharpening, and
				color adjustments at capture time, RAW preserves all the original data
				so photographers can make these decisions later in post-processing with
				maximum flexibility and quality.{" "}
				<a
					href="https://en.wikipedia.org/wiki/Raw_image_format"
					target="_blank"
					rel="noopener"
					className="underline hover:text-foreground transition-colors"
				>
					Source: Wikipedia
				</a>
			</>
		),
	},
	{
		question: "How does this converter work without full RAW processing?",
		answer:
			"Nearly every camera RAW file embeds a full-resolution JPEG preview that the camera generates at capture time. This tool extracts that embedded preview and lets you save it as JPG, PNG, WebP, or AVIF. You get a high-quality image instantly, without the complexity of full demosaicing. For exposure adjustments or white balance changes, use dedicated software like Lightroom or darktable.",
	},
	{
		question: "Which camera brands and RAW formats are supported?",
		answer:
			"Canon (CR2, CR3, CRW), Nikon (NEF, NRW), Sony (ARW, SR2), Adobe DNG, Fujifilm (RAF), Olympus (ORF), Pentax (PEF), Panasonic (RW2), Samsung (SRW), Epson (ERF), Minolta (MRW), Mamiya (MEF), Leaf (MOS), Kodak (KDC, DCR), Sigma (X3F), Hasselblad (3FR), and generic .raw files. Any RAW file with an embedded JPEG preview will work.",
	},
	{
		question:
			"Is the quality as good as processing RAW in Lightroom or darktable?",
		answer:
			"The embedded JPEG preview is generated by the camera's image processor with default settings applied (auto white balance, standard color profile, noise reduction). It looks identical to the JPG the camera would have saved in JPG mode. You cannot adjust exposure, highlights, or shadows after the fact like you can with full RAW editing software.",
	},
];

export default function RawConverterPage() {
	return (
		<ToolPageLayout
			title="Convert Camera RAW"
			description="Convert camera RAW files to JPG, PNG, WebP, or AVIF — free, private, no upload required."
		>
			<Suspense
				fallback={
					<div className="flex items-center justify-center h-[460px]">
						<Spinner className="size-6" />
					</div>
				}
			>
				<ImageConverterTool accept={ACCEPT} />
			</Suspense>

			<section className="mt-12 mb-8">
				<h2 className="text-lg font-semibold mb-2">About this tool</h2>
				<p className="text-muted-foreground">
					Extracts the embedded JPEG preview from camera RAW files. Supports
					Canon (CR2, CR3, CRW), Nikon (NEF, NRW), Sony (ARW, SR2), Adobe DNG,
					Fujifilm (RAF), Olympus (ORF), Pentax (PEF), Panasonic (RW2), and many
					more. For full RAW processing with white balance and exposure control,
					use Lightroom or darktable.
				</p>
			</section>

			<section>
				<h2 className="text-lg font-semibold mb-4">
					Frequently Asked Questions
				</h2>
				<Accordion type="multiple">
					{faqItems.map((item, i) => (
						// biome-ignore lint/suspicious/noArrayIndexKey: static FAQ list never changes
						<AccordionItem key={i} value={`faq-${i}`}>
							<AccordionTrigger>{item.question}</AccordionTrigger>
							<AccordionContent>
								<p className="text-muted-foreground">{item.answer}</p>
							</AccordionContent>
						</AccordionItem>
					))}
				</Accordion>
			</section>

			<LibraryAttribution browserApi="canvas" />
		</ToolPageLayout>
	);
}
